CREATE TYPE "FormaMesa" AS ENUM ('REDONDA', 'CUADRADA', 'RECTANGULAR');
CREATE TYPE "OrientacionMesa" AS ENUM ('HORIZONTAL', 'VERTICAL');

ALTER TABLE "Mesa"
  ADD COLUMN "forma" "FormaMesa" NOT NULL DEFAULT 'CUADRADA',
  ADD COLUMN "orientacion" "OrientacionMesa" NOT NULL DEFAULT 'HORIZONTAL',
  ADD COLUMN "tamanoVisual" INTEGER NOT NULL DEFAULT 2;
