import { BarChart3, CalendarDays, Download, PackageX, TrendingUp } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { ErrorState, LoadingState } from "../components/AsyncState";
import { money } from "../data/demo";
import { api, apiFailure } from "../lib/api";
import { useApp } from "../store/app";

type Summary = { cantidadVentas: number; totalVentas: number; totalPagado: number };
type Daily = { fecha: string; cantidadVentas: number; totalVentas: number };
type Product = { producto: string; cantidadVendida: number };
type Stock = { total: number };
const demoDays = [{ fecha: "Lun", totalVentas: 1280000, cantidadVentas: 38 }, { fecha: "Mar", totalVentas: 1740000, cantidadVentas: 51 }, { fecha: "Mié", totalVentas: 1510000, cantidadVentas: 46 }, { fecha: "Jue", totalVentas: 2130000, cantidadVentas: 62 }, { fecha: "Vie", totalVentas: 2860000, cantidadVentas: 85 }, { fecha: "Sáb", totalVentas: 3420000, cantidadVentas: 104 }, { fecha: "Dom", totalVentas: 2640000, cantidadVentas: 82 }];
const demoProducts = [{ producto: "Almuerzo ejecutivo", cantidadVendida: 84 }, { producto: "Hamburguesa El Mono", cantidadVendida: 67 }, { producto: "Pechuga a la plancha", cantidadVendida: 49 }, { producto: "Limonada de coco", cantidadVendida: 42 }];

function range(period: string) { const end = new Date(); const start = new Date(end); if (period === "semana") start.setDate(end.getDate() - 6); if (period === "mes") start.setDate(1); return { desde: start.toISOString().slice(0, 10), hasta: end.toISOString().slice(0, 10) }; }
export function ReportsPage() {
  const { session, branchId } = useApp(); const [period, setPeriod] = useState("semana"); const [loading, setLoading] = useState(!session?.demo); const [failure, setFailure] = useState<ReturnType<typeof apiFailure> | null>(null);
  const [summary, setSummary] = useState<Summary>(session?.demo ? { cantidadVentas: 487, totalVentas: 15640000, totalPagado: 15120000 } : { cantidadVentas: 0, totalVentas: 0, totalPagado: 0 });
  const [days, setDays] = useState<Daily[]>(session?.demo ? demoDays : []); const [products, setProducts] = useState<Product[]>(session?.demo ? demoProducts : []); const [stock, setStock] = useState(session?.demo ? 3 : 0);
  const load = useCallback(async () => { if (session?.demo || !branchId) return; await Promise.resolve(); setLoading(true); setFailure(null); try { const params = { ...range(period), sucursalId: branchId }; const [a,b,c,d] = await Promise.all([api.get<Summary>("/reportes/resumen",{params}),api.get<{datos:Daily[]}>("/reportes/ventas-diarias",{params}),api.get<{datos:Product[]}>("/reportes/productos-mas-vendidos",{params:{...params,limite:5}}),api.get<Stock>("/reportes/inventario-sin-stock",{params})]); setSummary(a.data); setDays(b.data.datos); setProducts(c.data.datos); setStock(d.data.total); } catch(error) { setFailure(apiFailure(error)); } finally { setLoading(false); } }, [branchId, period, session?.demo]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]); const max = Math.max(1, ...days.map((item) => item.totalVentas));
  if (loading) return <LoadingState label="Calculando reportes…"/>; if (failure) return <ErrorState detail={failure.message} requestId={failure.requestId} retry={() => void load()}/>;
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Analítica comercial</p><h1 className="page-title">Reportes</h1><p className="mt-2 text-sm text-denim/50">Ventas, productos y alertas reales de la sucursal seleccionada.</p></div><div className="flex gap-2"><select className="input h-12 w-auto" value={period} onChange={(event) => setPeriod(event.target.value)}><option value="hoy">Hoy</option><option value="semana">Esta semana</option><option value="mes">Este mes</option></select><button className="secondary h-12 w-auto px-4" disabled><Download size={17}/> Exportación próxima</button></div></header>
  <section className="grid gap-4 md:grid-cols-3"><article className="card"><TrendingUp className="text-emerald-600"/><p className="eyebrow mt-4">Ventas</p><strong className="mt-2 block text-3xl">{money.format(summary.totalVentas)}</strong><small className="text-denim/45">Pagado {money.format(summary.totalPagado)}</small></article><article className="card"><CalendarDays className="text-blue-600"/><p className="eyebrow mt-4">Operaciones</p><strong className="mt-2 block text-3xl">{summary.cantidadVentas}</strong><small className="text-denim/45">Ventas no anuladas</small></article><article className="card"><PackageX className="text-orange-600"/><p className="eyebrow mt-4">Sin existencias</p><strong className="mt-2 block text-3xl">{stock}</strong><small className="text-orange-600">Requieren revisión</small></article></section>
  <section className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><article className="card"><div className="flex items-center gap-2"><BarChart3/><h2 className="font-black">Ventas diarias</h2></div><div className="mt-8 flex h-64 items-end gap-3">{days.map((item) => <div key={item.fecha} className="flex h-full min-w-0 flex-1 flex-col justify-end gap-2"><span className="truncate text-center text-[10px] font-bold text-denim/45">{money.format(item.totalVentas)}</span><div className="rounded-t-xl bg-marigold" style={{ height: `${(item.totalVentas/max)*80}%` }}/><strong className="truncate text-center text-xs">{item.fecha.slice(5)}</strong></div>)}</div>{days.length === 0 && <p className="mt-10 text-sm text-denim/45">No hay ventas en el período.</p>}</article><article className="card"><h2 className="font-black">Más vendidos</h2><div className="mt-5 space-y-5">{products.map((product,index)=><div key={product.producto}><div className="flex justify-between gap-2 text-sm"><strong>{index+1}. {product.producto}</strong><span>{product.cantidadVendida} und.</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-denim/5"><div className="h-full rounded-full bg-steel" style={{width:`${Math.min(100,product.cantidadVendida)}%`}}/></div></div>)}</div></article></section></div>;
}
