import { BarChart3, CalendarDays, Download, PackageX, TrendingUp } from "lucide-react";
import { useState } from "react";
import { money } from "../data/demo";
const days = [{ day: "Lun", value: 1280000 }, { day: "Mar", value: 1740000 }, { day: "Mié", value: 1510000 }, { day: "Jue", value: 2130000 }, { day: "Vie", value: 2860000 }, { day: "Sáb", value: 3420000 }, { day: "Dom", value: 2640000 }];
const products = [{ name: "Almuerzo ejecutivo", units: 84 }, { name: "Hamburguesa El Mono", units: 67 }, { name: "Pechuga a la plancha", units: 49 }, { name: "Limonada de coco", units: 42 }];
export function ReportsPage() {
  const [period, setPeriod] = useState("semana"); const max = Math.max(...days.map((item) => item.value));
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Analítica comercial</p><h1 className="page-title">Reportes</h1><p className="mt-2 text-sm text-denim/50">Ventas, productos, pagos y alertas de inventario por sucursal.</p></div><div className="flex gap-2"><select className="input h-12 w-auto" value={period} onChange={(event) => setPeriod(event.target.value)}><option value="hoy">Hoy</option><option value="semana">Esta semana</option><option value="mes">Este mes</option></select><button className="secondary h-12 w-auto px-4"><Download size={17}/> Exportar</button></div></header>
  <section className="grid gap-4 md:grid-cols-3"><article className="card"><TrendingUp className="text-emerald-600"/><p className="eyebrow mt-4">Ventas netas</p><strong className="mt-2 block text-3xl">{money.format(15640000)}</strong><small className="text-emerald-600">↑ 12,4% vs. período anterior</small></article><article className="card"><CalendarDays className="text-blue-600"/><p className="eyebrow mt-4">Pedidos atendidos</p><strong className="mt-2 block text-3xl">487</strong><small className="text-denim/45">Ticket promedio {money.format(32115)}</small></article><article className="card"><PackageX className="text-orange-600"/><p className="eyebrow mt-4">Sin existencias</p><strong className="mt-2 block text-3xl">3</strong><small className="text-orange-600">Requieren revisión</small></article></section>
  <section className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><article className="card"><div className="flex items-center gap-2"><BarChart3/><h2 className="font-black">Ventas diarias</h2></div><div className="mt-8 flex h-64 items-end gap-3">{days.map((item) => <div key={item.day} className="flex h-full flex-1 flex-col justify-end gap-2"><span className="text-center text-[10px] font-bold text-denim/45">{money.format(item.value)}</span><div className="rounded-t-xl bg-marigold" style={{ height: `${(item.value / max) * 80}%` }}/><strong className="text-center text-xs">{item.day}</strong></div>)}</div></article><article className="card"><h2 className="font-black">Más vendidos</h2><div className="mt-5 space-y-5">{products.map((product, index) => <div key={product.name}><div className="flex justify-between text-sm"><strong>{index + 1}. {product.name}</strong><span>{product.units} und.</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-denim/5"><div className="h-full rounded-full bg-steel" style={{ width: `${product.units}%` }}/></div></div>)}</div></article></section></div>;
}
