import { Building2, CheckCircle2, FileBadge2, Save, ShieldCheck, Store } from "lucide-react";
import { useState } from "react";
import toast from "react-hot-toast";
export function SettingsPage() {
  const [tab, setTab] = useState<"operacion" | "fiscal" | "seguridad">("operacion");
  return <div className="space-y-6"><header><p className="eyebrow">Administración</p><h1 className="page-title">Configuración</h1><p className="mt-2 text-sm text-denim/50">Parámetros separados por restaurante y sucursal.</p></header><div className="flex flex-wrap gap-2">{([{ id: "operacion", label: "Operación", icon: Store }, { id: "fiscal", label: "Perfil fiscal", icon: FileBadge2 }, { id: "seguridad", label: "Accesos", icon: ShieldCheck }] as const).map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`secondary h-11 w-auto px-4 ${tab === id ? "bg-steel text-white" : ""}`}><Icon size={17}/>{label}</button>)}</div>
  {tab === "operacion" && <section className="card max-w-4xl"><div className="flex items-center gap-3"><Building2/><div><h2 className="font-black">La Carolina</h2><p className="text-xs text-denim/45">La configuración de sucursal prevalece sobre la del restaurante.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Zona horaria<select className="input mt-2"><option>America/Bogota</option></select></label><label className="text-sm font-bold">Impuesto al consumo<input className="input mt-2" type="number" defaultValue="8"/></label><label className="text-sm font-bold">Moneda<select className="input mt-2"><option>COP · Peso colombiano</option></select></label><label className="text-sm font-bold">Propina sugerida<input className="input mt-2" type="number" defaultValue="10"/></label></div><button onClick={() => toast.success("Configuración guardada y registrada en auditoría")} className="primary mt-6 w-auto px-6"><Save size={18}/> Guardar cambios</button></section>}
  {tab === "fiscal" && <section className="grid gap-4 lg:grid-cols-2"><article className="card"><p className="eyebrow">Estado de preparación</p><h2 className="mt-2 text-xl font-black">Facturación electrónica</h2><div className="mt-5 space-y-3">{["Datos fiscales del restaurante", "Responsabilidades tributarias", "Resolución de numeración"].map((item) => <div className="flex items-center gap-2 text-sm" key={item}><CheckCircle2 size={17} className="text-emerald-600"/>{item}</div>)}<div className="rounded-xl bg-orange-50 p-3 text-sm text-orange-800">Pendiente: credenciales del proveedor tecnológico en etapa de pruebas.</div></div></article><article className="card"><h2 className="font-black">Separación fiscal segura</h2><p className="mt-3 text-sm leading-relaxed text-denim/55">Guardar una factura operativa no la envía a DIAN. Preparar, numerar, encolar y consultar el documento electrónico son acciones distintas y controladas.</p></article></section>}
  {tab === "seguridad" && <section className="card max-w-4xl"><h2 className="font-black">Roles y capacidades</h2><p className="mt-2 text-sm text-denim/50">El administrador asigna permisos; el plan contratado limita las capacidades disponibles.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{["Administrador · acceso completo", "Cajero · ventas, pagos y archivo", "Mesero · mesas y pedidos", "Cocina · comandas", "Contador · consulta y exportación", "Domiciliario · entregas"].map((role) => <div key={role} className="rounded-xl border border-denim/10 p-4 text-sm font-bold">{role}</div>)}</div></section>}</div>;
}
